package com.aboff.core.repository.dh;

import org.junit.jupiter.api.Test;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Method;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Structural guard for SRD content gating: every repository {@code @Query} whose FROM clause
 * names a gated entity must bind {@code :includeNonSrd}, or be explicitly allowlisted with a
 * real reason.
 * <p>
 * This does not verify the predicate is <em>correct</em> — only that it exists. Its job is to
 * make it impossible to ship a new (or modified) catalogue query against a gated entity that
 * silently omits SRD gating, across the roughly twenty repositories and one hundred-plus
 * {@code @Query} methods in {@code repository.dh}, without anyone having to remember to check.
 * </p>
 * <p>
 * The scan walks {@code repository.dh}'s compiled classes directly rather than going through
 * Spring's {@code ClassPathScanningCandidateComponentProvider} — that provider's default
 * candidate filter excludes interfaces (it requires {@code isConcrete()}), which is exactly
 * everything in this package, and working around that filter is more fragile than reading the
 * classpath directory. {@link #testFewerThan20RepositoriesMeansTheScanIsBroken()} exists so a
 * scan that silently finds nothing can never masquerade as a passing test.
 * </p>
 */
class SrdPredicateCoverageTest {

    private static final String REPOSITORY_PACKAGE = "com.aboff.core.repository.dh";

    /**
     * JPQL entity names (not table names) that carry SRD gating. Mirrors the entity list from
     * the SRD content gating design doc: the four {@link com.aboff.core.model.entity.dh.Card}
     * subtypes, the four {@link com.aboff.core.model.entity.dh.BaseItem} subtypes, and the
     * twelve standalone gated entities.
     */
    private static final Set<String> GATED_ENTITIES = Set.of(
            "Card", "AncestryCard", "CommunityCard", "SubclassCard", "DomainCard",
            "Weapon", "Armor", "Loot", "MartialStance",
            "Domain", "Class", "SubclassPath", "TransformationCard", "Question", "CardCostTag", "Feature",
            "Adversary", "Environment", "Beastform", "Condition", "Encounter");

    /** Matches the entity name immediately following a JPQL {@code FROM} keyword. */
    private static final Pattern FROM_ENTITY_PATTERN = Pattern.compile("\\bfrom\\s+(\\w+)", Pattern.CASE_INSENSITIVE);

    /**
     * Queries that name a gated entity in their FROM clause but do not (yet) bind
     * {@code :includeNonSrd}, keyed {@code "RepositoryInterface#methodName"}.
     * <p>
     * Each workstream removes its own entries as it adds the predicate. An entry that
     * stays must carry a real reason (e.g. "custom-content-only query; no official rows
     * can match"), not "not done yet".
     * </p>
     * <p>
     * Every entry below was generated by running this test's own scan against the
     * pre-gating codebase, so this allowlist starts as an exact snapshot of every gated
     * query that exists at handoff time — nothing here is a guess.
     * </p>
     */
    private static final Map<String, String> ALLOWED_UNGATED_QUERIES = Map.ofEntries(
            // Workstream E (GM content): AdversaryRepository
            Map.entry("AdversaryRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds AdversaryService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("AdversaryRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("AdversaryRepository#findByCreatedByIdAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through AdversaryService#toResponse rather than relying on a repository-level predicate. (Not a custom-content-only query: AdversaryService#createAdversary sets createdBy unconditionally before the isOfficial branch, so an ADMIN who authors an official adversary is also its createdBy and this query could return official rows.)"),
            Map.entry("AdversaryRepository#findByOriginalAdversaryIdAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through AdversaryService#toResponse rather than relying on a repository-level predicate."),
            Map.entry("AdversaryRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through AdversaryService#toResponse rather than relying on a repository-level predicate."),
            Map.entry("AdversaryRepository#findAllByIdInWithFeatures", "Feeds EncounterRunService#toAdversaryStatBlock, which applies ContentAccessService#mayView and ContentRedaction#stub itself before building the stat block (mirroring AdversaryService#toResponse's own gate) -- see that method's javadoc for why it applies the gate directly instead of delegating to AdversaryService#toResponse."),
            Map.entry("AdversaryRepository#findAllByIdInWithExperiences", "Feeds EncounterRunService#toAdversaryStatBlock, which applies ContentAccessService#mayView and ContentRedaction#stub itself before building the stat block (mirroring AdversaryService#toResponse's own gate) -- see that method's javadoc for why it applies the gate directly instead of delegating to AdversaryService#toResponse."),
            // Workstream B (Cards): AncestryCardRepository
            Map.entry("AncestryCardRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("AncestryCardRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds AncestryCardService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("AncestryCardRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through AncestryCardService#toResponse rather than relying on a repository-level predicate."),
            // Workstream C (Items): ArmorRepository
            Map.entry("ArmorRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("ArmorRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds ArmorService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("ArmorRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through ArmorService#toResponse rather than relying on a repository-level predicate."),
            // Workstream E (GM content): BeastformRepository
            Map.entry("BeastformRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds BeastformService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("BeastformRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("BeastformRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through BeastformService#toResponse rather than relying on a repository-level predicate."),
            // Workstream D (Catalogue): CardCostTagRepository
            Map.entry("CardCostTagRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("CardCostTagRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds CardCostTagService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("CardCostTagRepository#findAllByIdInAndDeletedAtIsNull", "Called from CardCostTagService#resolveCostTags; the resolved tags are attached to the caller's owning entity (e.g. a card's costTags) and only ever surfaced again through that entity's own toResponse, which embeds CardCostTagService#toResponse and redacts there -- never returned raw."),
            Map.entry("CardCostTagRepository#findByLabelIgnoreCaseAndDeletedAtIsNull", "Feeds the find-or-create lookup in CardCostTagService#findOrCreate; the resolved tag is attached to a parent entity and only ever surfaced through that parent's own toResponse, never returned directly."),
            // Workstream D (Catalogue): ClassRepository
            Map.entry("ClassRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("ClassRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds ClassService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("ClassRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through ClassService#toResponse rather than relying on a repository-level predicate."),
            // Workstream B (Cards): CommunityCardRepository
            Map.entry("CommunityCardRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("CommunityCardRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds CommunityCardService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("CommunityCardRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through CommunityCardService#toResponse rather than relying on a repository-level predicate."),
            // Workstream E (GM content): ConditionRepository
            Map.entry("ConditionRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds ConditionService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("ConditionRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("ConditionRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through ConditionService#toResponse rather than relying on a repository-level predicate."),
            // Workstream B (Cards): DomainCardRepository
            Map.entry("DomainCardRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("DomainCardRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds DomainCardService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("DomainCardRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through DomainCardService#toResponse rather than relying on a repository-level predicate."),
            // Workstream D (Catalogue): DomainRepository
            Map.entry("DomainRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("DomainRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds DomainService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("DomainRepository#findAllByIdInAndDeletedAtIsNull", "Called from SubclassPathService (create/bulk-create/update/findOrCreate) and ClassService (create/update) to resolve associatedDomains; the resolved domains are attached to the caller's own entity and only ever surfaced again through that entity's own toResponse (SubclassPathService/ClassService), which routes an expand through DomainService#toResponse and redacts there -- never returned raw."),
            // Workstream E (GM content): EncounterRepository
            Map.entry("EncounterRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds EncounterService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("EncounterRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("EncounterRepository#findByCampaignIdAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through EncounterService#toResponse rather than relying on a repository-level predicate."),
            Map.entry("EncounterRepository#findByOriginalEncounterIdAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through EncounterService#toResponse rather than relying on a repository-level predicate."),
            // Workstream E (GM content): EnvironmentRepository
            Map.entry("EnvironmentRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds EnvironmentService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("EnvironmentRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("EnvironmentRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through EnvironmentService#toResponse rather than relying on a repository-level predicate."),
            // Workstream D (Catalogue): FeatureRepository
            Map.entry("FeatureRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("FeatureRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds FeatureService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("FeatureRepository#findAllByIdInAndDeletedAtIsNull", "No current caller returns these directly; every current caller (ClassService, TransformationCardService, item services, ...) routes the resolved features back through its own toResponse, which embeds FeatureService#toResponse and redacts there."),
            Map.entry("FeatureRepository#findByNameIgnoreCaseAndExpansionIdAndFeatureTypeAndDescriptionAndDeletedAtIsNull", "Feeds the find-or-create lookup in FeatureService#findOrCreate; the resolved feature is attached to a parent entity and only ever surfaced through that parent's own toResponse (which embeds FeatureService#toResponse), never returned directly."),
            // Workstream C (Items): LootRepository
            Map.entry("LootRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("LootRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds LootService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("LootRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through LootService#toResponse rather than relying on a repository-level predicate."),
            // Workstream C (Items): MartialStanceRepository
            Map.entry("MartialStanceRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("MartialStanceRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds MartialStanceService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("MartialStanceRepository#findAllByIdInAndDeletedAtIsNull", "Batch fetch used only by CharacterSheetService to resolve known martial stances; results are routed through MartialStanceService#toResponse before being returned, which redacts non-SRD content directly."),
            // Workstream D (Catalogue): QuestionRepository
            Map.entry("QuestionRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("QuestionRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds QuestionService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("QuestionRepository#findAllByIdInAndDeletedAtIsNull", "Called from QuestionService#resolveQuestions, itself called from ClassService and TransformationCardService; the resolved questions are attached to the caller's owning entity and only ever surfaced again through that entity's own toResponse, never returned raw."),
            Map.entry("QuestionRepository#findByQuestionTextIgnoreCaseAndExpansionIdAndQuestionTypeAndDeletedAtIsNull", "Feeds the find-or-create lookup in QuestionService#findOrCreate; the resolved question is attached to a parent entity and only ever surfaced through that parent's own toResponse, never returned directly."),
            // Workstream B (Cards): SubclassCardRepository
            Map.entry("SubclassCardRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("SubclassCardRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds SubclassCardService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("SubclassCardRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through SubclassCardService#toResponse rather than relying on a repository-level predicate."),
            // Workstream D (Catalogue): SubclassPathRepository
            Map.entry("SubclassPathRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds SubclassPathService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("SubclassPathRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("SubclassPathRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through SubclassPathService#toResponse rather than relying on a repository-level predicate."),
            // Workstream D (Catalogue): TransformationCardRepository
            Map.entry("TransformationCardRepository#findAllWithExpansion", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("TransformationCardRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds TransformationCardService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("TransformationCardRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through TransformationCardService#toResponse rather than relying on a repository-level predicate."),
            // Workstream C (Items): WeaponRepository
            Map.entry("WeaponRepository#findAllWithFilters", "includeDeleted=true administrative listing; ContentAccessService#resolveIncludeDeleted() makes this unreachable below MODERATOR, and by design privileged admin listings bypass SRD filtering entirely."),
            Map.entry("WeaponRepository#findByIdAndDeletedAtIsNull", "Single-entity fetch; feeds WeaponService#toResponse, which redacts non-SRD content directly. Not a list/browse query."),
            Map.entry("WeaponRepository#findAllByIdInAndDeletedAtIsNull", "No current caller in the codebase; any future caller must route results through WeaponService#toResponse rather than relying on a repository-level predicate."));

    @Test
    void testFewerThan20RepositoriesMeansTheScanIsBroken() {
        List<Class<?>> repositories = scanRepositoryInterfaces();

        assertThat(repositories.size())
                .as("repository.dh scan found %d interfaces; expected at least 20. "
                        + "A broken scan (e.g. a wrong classpath directory) must fail loudly rather "
                        + "than silently pass with zero repositories checked.", repositories.size())
                .isGreaterThanOrEqualTo(20);
    }

    @Test
    void everyGatedQueryBindsIncludeNonSrdOrIsExplicitlyAllowlisted() {
        List<Class<?>> repositories = scanRepositoryInterfaces();
        List<String> offenders = new ArrayList<>();

        for (Class<?> repository : repositories) {
            for (Method method : repository.getDeclaredMethods()) {
                Query query = method.getAnnotation(Query.class);
                if (query == null) {
                    continue;
                }

                if (!namesGatedEntity(query.value()) && !namesGatedEntity(query.countQuery())) {
                    continue;
                }

                boolean bindsIncludeNonSrd = query.value().contains(":includeNonSrd")
                        || query.countQuery().contains(":includeNonSrd");
                if (bindsIncludeNonSrd) {
                    continue;
                }

                String key = repository.getSimpleName() + "#" + method.getName();
                if (!ALLOWED_UNGATED_QUERIES.containsKey(key)) {
                    offenders.add(key);
                }
            }
        }

        if (!offenders.isEmpty()) {
            fail(describeOffenders(offenders));
        }
    }

    /**
     * Returns true if the given JPQL string's FROM clause names one of {@link #GATED_ENTITIES}.
     * A blank or null string (as {@code countQuery()} is when unset) names nothing.
     *
     * @param jpql the query text to inspect; may be null or blank
     * @return true if a gated entity appears immediately after a {@code FROM} keyword
     */
    private boolean namesGatedEntity(String jpql) {
        if (jpql == null || jpql.isBlank()) {
            return false;
        }
        Matcher matcher = FROM_ENTITY_PATTERN.matcher(jpql);
        while (matcher.find()) {
            if (GATED_ENTITIES.contains(matcher.group(1))) {
                return true;
            }
        }
        return false;
    }

    /**
     * Loads every {@code interface} in {@link #REPOSITORY_PACKAGE} that implements Spring
     * Data's {@link Repository} marker, by reading the compiled {@code .class} files from the
     * test classpath directly.
     * <p>
     * Deliberately not {@code ClassPathScanningCandidateComponentProvider}: its default
     * candidate filter requires {@code isConcrete()}, which excludes every interface in this
     * package outright, and overriding that filter is more fragile than a directory listing.
     * </p>
     * <p>
     * Uses {@code getResources} (plural), not {@code getResource}: this test class lives in the
     * same package it scans ({@code com.aboff.core.repository.dh}), under {@code test-classes}
     * rather than {@code classes}. Both directories match the package path and both are on the
     * classpath, so the singular, first-match {@code getResource} can resolve to
     * {@code test-classes}' copy of the package — which contains only this test class — and
     * silently miss every real repository in {@code target/classes}. Merging every matching
     * directory sidesteps that classpath-ordering trap entirely.
     * </p>
     *
     * @return the repository interfaces found; never null, possibly empty if the scan itself
     *         is broken (see {@link #testFewerThan20RepositoriesMeansTheScanIsBroken()})
     */
    private List<Class<?>> scanRepositoryInterfaces() {
        String packagePath = REPOSITORY_PACKAGE.replace('.', '/');
        List<Class<?>> repositories = new ArrayList<>();

        try {
            Enumeration<URL> packageUrls = Thread.currentThread().getContextClassLoader().getResources(packagePath);
            while (packageUrls.hasMoreElements()) {
                repositories.addAll(loadRepositoriesFrom(packageUrls.nextElement()));
            }
        } catch (IOException e) {
            throw new IllegalStateException("Failed to enumerate classpath resources for " + packagePath, e);
        }

        return repositories;
    }

    /**
     * Loads every {@link Repository} interface whose compiled {@code .class} file sits directly
     * in the given package directory.
     *
     * @param packageDirUrl a {@code file:} URL for one classpath entry's copy of the package
     *                      directory
     * @return the repository interfaces found in that directory; empty if none
     */
    private List<Class<?>> loadRepositoriesFrom(URL packageDirUrl) {
        File packageDir = new File(packageDirUrl.getFile());
        File[] classFiles = packageDir.listFiles((dir, name) -> name.endsWith(".class"));
        if (classFiles == null) {
            return List.of();
        }

        List<Class<?>> repositories = new ArrayList<>();
        for (File classFile : classFiles) {
            String simpleName = classFile.getName().substring(0, classFile.getName().length() - ".class".length());
            String className = REPOSITORY_PACKAGE + "." + simpleName;
            try {
                Class<?> candidate = Class.forName(className);
                if (candidate.isInterface() && Repository.class.isAssignableFrom(candidate)) {
                    repositories.add(candidate);
                }
            } catch (ClassNotFoundException e) {
                throw new IllegalStateException("Failed to load scanned class: " + className, e);
            }
        }
        return repositories;
    }

    /**
     * Formats the offending method list for a clear, actionable test failure message.
     *
     * @param offenders the "RepositoryInterface#methodName" keys that failed the check
     * @return a multi-line failure message listing every offender
     */
    private String describeOffenders(List<String> offenders) {
        StringBuilder message = new StringBuilder();
        message.append(offenders.size())
                .append(offenders.size() == 1 ? " query names" : " queries name")
                .append(" a gated entity in its FROM clause but neither binds :includeNonSrd nor")
                .append(" appears in ALLOWED_UNGATED_QUERIES:\n");
        offenders.stream().sorted().forEach(offender -> message.append("  - ").append(offender).append('\n'));
        message.append("Fix: add the :includeNonSrd predicate to the query, or add a real reason to ")
                .append("ALLOWED_UNGATED_QUERIES in ").append(SrdPredicateCoverageTest.class.getSimpleName())
                .append('.');
        return message.toString();
    }
}
