ALTER TABLE weapons ADD COLUMN tier INTEGER NOT NULL DEFAULT 1;
ALTER TABLE armors ADD COLUMN tier INTEGER NOT NULL DEFAULT 1;
ALTER TABLE loot ADD COLUMN tier INTEGER NOT NULL DEFAULT 1;

ALTER TABLE weapons ADD CONSTRAINT chk_weapons_tier CHECK (tier BETWEEN 1 AND 4);
ALTER TABLE armors ADD CONSTRAINT chk_armors_tier CHECK (tier BETWEEN 1 AND 4);
ALTER TABLE loot ADD CONSTRAINT chk_loot_tier CHECK (tier BETWEEN 1 AND 4);
